### ISSUE TITLE
Switch from datomic to datascript.

### ISSUE THREAD

**Issue by ghost** [kovasb/session#45]
I think we could gain a lot by moving as much as possible into the browser.
Making the server part as lightweight as possible.

A server part would only be required for evaluating code and saving files.
Note that this would also allow for evaluating code in different clojure implementations or running instances from within the same session.

Additionally people wouldn't be required to use datomic and the datomic gotcha could be avoided.

Thoughts?

**Comment by kovasb** [comment]
No longer relevant for the new version.

**Comment by GetContented** [comment]
What is the new version? is it imminent? Is it a rewrite using om-next?
